# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PASS_GIT}}
      - name: Deploy nest js
        uses: appleboy/ssh-action@v0.1.2
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          RABBITMQ_URL: ${{secrets.RABBITMQ_URL}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: MONGODB_URI,RABBITMQ_URL
          script: |
            rm -R -f lgt-travel-catalog
            git clone https://${{secrets.USERNAME_GIT}}:${{secrets.PASS_GIT}}@github.com/2110521-2564-1-SW-ARCH/lgt-travel-catalog.git
            cd lgt-travel-catalog
            docker-compose down -v
            touch .env
            echo "MONGODB_URI=$MONGODB_URI" >> .env
            echo "RABBITMQ_URL=$RABBITMQ_URL" >> .env
            docker-compose build
            docker-compose up -d
            echo 'Deployment prod complete'
